[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/emacs"]
    type = "git-repo"
    url = "https://github.com/SnichOne/dotemacs"
    refreshPeriod = "24h"
